### ISSUE TITLE
The changed code is missing in the PR on SonarCloud for Java repositories

### ISSUE THREAD

**Issue by TaurMorchant** [Netcracker/qubership-core-infra#8]

**Comment by TaurMorchant** [comment]
Analysys result:
Дело в том, что в devops-овском workflow action `maven-publish` есть вот такой блок:
```
inputs:
    ref:
        required: false
        type: string
        default: "main"
...
- name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref}}
          fetch-depth: 0
```
Суть в том, что если не передавать ничего в параметр ref при запуске maven-publish, он выкачивает всегда main бранч. И это нормально работает для самого мейна, coverage считается. Но вот если завести PR, то во время выполнения workflow опять же выкачается main, в не бранч, из которого создан PR. И sonar сделает git diff мейна с мейном, увидит, что изменений нет и напишет, что в PR никакой код не изменен. А раз изменений нет, то и coverage нет.

Надо поправить workflow во всех наших репах, добавив в параметры запуска maven-publish
```
ref: ${{ github.head_ref }}
```
